### ISSUE TITLE
All lookups returning Error

### ISSUE THREAD

**Issue by Zengor** [itayperl/radical-lookup#2]
I'm guessing this has been abandoned but I figured I would report anyway that all lookups in the live version are returning "Error!"
![image](https://user-images.githubusercontent.com/7103539/29239171-e76c8244-7f1d-11e7-9175-ec51a2c3324f.png)

Anyway, even if you're not going to look into it, thank you for making this great tool!

**Comment by itayperl** [comment]
Back online now :)
Thanks!
